apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-prod
  namespace: devops-tools

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prod
  name: prod-pod-management
rules:
- apiGroups: ["*"] 
  resources: ["deployments"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-prod-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: jenkins-prod
  namespace: devops-tools
roleRef:
  kind: Role
  name: prod-pod-management
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-prod-token
  namespace: devops-tools
  annotations:
    kubernetes.io/service-account.name: jenkins-prod
type: kubernetes.io/service-account-token

