server {
        listen       10443 ssl;
        server_name  ssl.test.com;
        root         /usr/share/nginx/html;
        ssl_certificate "/etc/nginx/ssl/ssl.test.com.crt";
        ssl_certificate_key "/etc/nginx/ssl/ssl.test.com.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
}