apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
  - name: https-client-config
    literals:
      - APP_ENV=uat

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: https-client
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "-URL"
          - "https://ssl.test.com:50443"
      - op: add
        path: /spec/template/spec/hostAliases
        value:
          - ip: "172.18.0.1"
            hostnames:
              - "ssl.test.com"
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: ssl-test-web-crt
          secret:
            secretName: ssl-test-web-crt
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: ssl-certs
          mountPath: /etc/ssl/certs/
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: ssl-certs
          emptyDir: {}
      - op: add
        path: /spec/template/spec/initContainers
        value:
          - name: init-container
            image: debian
            command: ["/bin/sh", "-c", "update-ca-certificates --fresh && cp -r /etc/ssl/certs/* /mnt/ssl-certs/" ]
            securityContext:
              runAsUser: 0
              readOnlyRootFilesystem: false
            volumeMounts:
              - name: ssl-test-web-crt
                mountPath: /usr/local/share/ca-certificates/
              - name: ssl-certs
                mountPath: /mnt/ssl-certs

images:
  - name: https-client
    newTag: v1.0
    newName: https-client
  - name: debian
    newTag: upca
    newName: debian