apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
spec:
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      labels:
        app: http-client
    spec:
      containers:
      - name: http-client
        image: http-client:v1.0
        args:
        - URL
        - "https://baidu.com"