apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
  - name: https-client-config
    literals:
      - APP_ENV=prod

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: https-client
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "-URL"
          - "https://baidu.com"

images:
  - name: https-client
    newTag: v1.0
    newName: https-client