apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: http-client-config
    literals:
      - APP_ENV=prod

patchesStrategicMerge:
  - deployment-patch.yaml


