apiVersion: v1
kind: Secret
metadata:
  name: my-harbor-tls
  namespace: devops-tools  # Specify your namespace
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYrekNDQStPZ0F3SUJBZ0lVQ1lGeTc3T05v
    ZkpVaWZ3WkdIWW53V2UvUFh3d0RRWUpLb1pJaHZjTkFRRU4KQlFBd2NERUxNQWtHQTFVRUJoTUNR
    MDR4RURBT0JnTlZCQWdNQjBKbGFXcHBibWN4RURBT0JnTlZCQWNNQjBKbAphV3BwYm1jeEVEQU9C
    Z05WQkFvTUIyVjRZVzF3YkdVeEVUQVBCZ05WQkFzTUNGQmxjbk52Ym1Gc01SZ3dGZ1lEClZRUURE
    QTlvWVhKaWIzSXVhemh6TG1SbGJXOHdIaGNOTWpRd09ESXlNVEExTkRJeldoY05NelF3T0RJd01U
    QTEKTkRJeldqQndNUXN3Q1FZRFZRUUdFd0pEVGpFUU1BNEdBMVVFQ0F3SFFtVnBhbWx1WnpFUU1B
    NEdBMVVFQnd3SApRbVZwYW1sdVp6RVFNQTRHQTFVRUNnd0haWGhoYlhCc1pURVJNQThHQTFVRUN3
    d0lVR1Z5YzI5dVlXd3hHREFXCkJnTlZCQU1NRDJoaGNtSnZjaTVyT0hNdVpHVnRiekNDQWlJd0RR
    WUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0MKQWdvQ2dnSUJBTElGcmpCdDI1S2Y4aVNaU01LbGRY
    b3RhOFYrUnVxeitVU0E3aWkraStIN1FwTzhLdWRVT2UxMgpqSEdqaU5Xem0xa3RnRk1YODYvYndo
    dGVXU3YxNDB3OUtaMUFCeDllU1R3UUdDZ3FjWmJ1ejZLRzBxL3RyLzM1ClBLVTcrelE1enZEeFdB
    bkxFQ1Q3WFZBUnVoRzQybzNXY1JyM1VkVlhNSDFwYkhCeTFHMlpPWklocVNFY3liQlUKOWhFc0I4
    dllhL05kdURBa2tzTVVGbStxd0VaUHRHVFBydTJiSG5jdTJqMjNGRHkyV0tscjg5MTFMWERwWFhJ
    RApOY3VvUDlGUzUwNnpsQy9JVWtGK2FBRnZCQmdDN1hLK2ZVV2w5R3ZoVFlUcTZtQVVCNVlBQ25p
    S0pXcUI5YndTCjFRWjlLc3piblJzNkRaZUVBY0FPelV5NWw2VU9OVkVqMHhsdXRyQkZCblhCanhQ
    dmVIRHdUcDFiWFE1R2tQdG8KNk5lclRqSnova1E4QkhPWlJIWFg4b3RRY0xEWXgvUlY2eGFLbW53
    aEM4MUZVS2J6NXB0dzRleDAvNmZCbmxGTApQQmM3RTR4cmFCSktjM1lkcEtPV0VjRXFmSG9kQnk2
    MUVtaWJlQzJudTlKVGc1V0ZlaEFnbWtrdVdabWU1dGl4ClU2ZTZYc0NyUGNtY3p4SC8rMW5QMFdh
    VTdVTWpCUjI0RWU3cnFHaFFRV25lSWtTakpVTWV2VjM1OTVDNFN3YlQKRUNyQkhvWW1RVFg2YmlY
    c2JKNGNrL1poRTVhOEdaS3FoUXhDTlV0aE9GYmQwSzlScWZ3b1ZVeFoyOWRZeDNMNApuQlhGblE3
    OENUQzFSQmx0NW1SNzB3T0ptWC92R2QzMG1ianNNVWdYY1AxbzE3YkhvM1FEQWdNQkFBR2pnWXd3
    CmdZa3dId1lEVlIwakJCZ3dGb0FVaHJPdVAybFBxWmVWSXBsRXpjWXAybDZYdWRFd0NRWURWUjBU
    QkFJd0FEQUwKQmdOVkhROEVCQU1DQlBBd0V3WURWUjBsQkF3d0NnWUlLd1lCQlFVSEF3RXdHZ1lE
    VlIwUkJCTXdFWUlQYUdGeQpZbTl5TG1zNGN5NWtaVzF2TUIwR0ExVWREZ1FXQkJUS3dmVzFuWlBJ
    ZTZLZjdBd1d2bVQzN2U1OFdEQU5CZ2txCmhraUc5dzBCQVEwRkFBT0NBZ0VBRjZJQUhPcVdnVldR
    SWVtRE5lYUhMd053VDRKNUNFT1hncFJZSWg2eFo0RTcKTXVZV1QyelZOUGRRVkw5SkhXaU5aNHdz
    S1pzcWpzd0JQR3JVY2FRRlYwdjdzR0ZWK1VCSmFtbzRPSG1TeWE1eAp2K013ajQ2QXZhRVA0cnNY
    Mlp4UWhFWEVPRUhOcDUwclRpalJBZGRwNjNrcDVsRzBHTW5nQlRzdjEzN1RqVUlxCnRBS3RQSFRS
    VUk3UEhseG93eTBnNU1TZFNGMzZoeEhqMnJHK1grbVhsdWhXQmQvTUx5ck5oYTNaWWZlMTRGU2kK
    aXAyTE9VVGVndi9NRzBPaFpBT2VHYyt6UDh5ZUpYME9RSTFtTVBiTitUeVFxMUNLZVpnM3l4RklB
    L3dkekRDSwpTMHF2dkpLVU1admk1K1hhaDBtb2NyOUlrVFVOSnNLVU0wbmVHQ2t5SmdVaUF5ekNS
    bTRiUzh3Nm8zYi9zdjIrCnY4bXplNWNlOTBla2NCb0tHQksrT21YNXZGOFI4R3N3L1MwZUxFSlgz
    L3JtRHBqM1pNeTFkR2NyVHBBT1cyVFYKRk0vZzZ6QU5JT1ZNUys0OFphYUVHL3Zudk5sVXp6YU83
    cUN4cFpEazZzV3RsRTFSeVNZUTZmK0NGazJKV25sRgo2MWR0cnpkOXBsMjI5UXhuUmJnTzh5WDVQ
    dUh6bTI1ZStMOS92ditad1NWN3I3K3IrOGYrdXA1WU1adWIvNzI2CjFGMkhjWndGS1BSQlo2Znlj
    STZpMm9nZktMbmdzSTVxZDlkTmFhc0laNm1VdEsyUzJ3bnp4dk1sRVd2bXVqZU8KT1dIMkF2dnhw
    dXhZMnRNNm1Kbm5nZE9xVk9hL0x5MFljQVNKOGVnc2s5YjRtZHUzeCtqVzFNU05ZN2s1ZzI0PQot
    LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpSQUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1M0d2dna3FBZ0VBQW9JQ0FRQ3lCYTR3YmR1U24vSWsKbVVqQ3BYVjZMV3ZGZmticXMvbEVn
    TzRvdm92aCswS1R2Q3JuVkRudGRveHhvNGpWczV0WkxZQlRGL092MjhJYgpYbGtyOWVOTVBTbWRR
    QWNmWGtrOEVCZ29LbkdXN3MraWh0S3Y3YS85K1R5bE8vczBPYzd3OFZnSnl4QWsrMTFRCkVib1J1
    TnFOMW5FYTkxSFZWekI5YVd4d2N0UnRtVG1TSWFraEhNbXdWUFlSTEFmTDJHdnpYYmd3SkpMREZC
    WnYKcXNCR1Q3Umt6Njd0bXg1M0x0bzl0eFE4dGxpcGEvUGRkUzF3NlYxeUF6WExxRC9SVXVkT3M1
    UXZ5RkpCZm1nQgpid1FZQXUxeXZuMUZwZlJyNFUyRTZ1cGdGQWVXQUFwNGlpVnFnZlc4RXRVR2ZT
    ck0yNTBiT2cyWGhBSEFEczFNCnVaZWxEalZSSTlNWmJyYXdSUVoxd1k4VDczaHc4RTZkVzEwT1Jw
    RDdhT2pYcTA0eWMvNUVQQVJ6bVVSMTEvS0wKVUhDdzJNZjBWZXNXaXBwOElRdk5SVkNtOCthYmNP
    SHNkUCtud1o1UlN6d1hPeE9NYTJnU1NuTjJIYVNqbGhIQgpLbng2SFFjdXRSSm9tM2d0cDd2U1U0
    T1ZoWG9RSUpwSkxsbVpudWJZc1ZPbnVsN0FxejNKbk04Ui8vdFp6OUZtCmxPMURJd1VkdUJIdTY2
    aG9VRUZwM2lKRW95VkRIcjFkK2ZlUXVFc0cweEFxd1I2R0prRTErbTRsN0d5ZUhKUDIKWVJPV3ZC
    bVNxb1VNUWpWTFlUaFczZEN2VWFuOEtGVk1XZHZYV01keStKd1Z4WjBPL0Frd3RVUVpiZVprZTlN
    RAppWmwvN3huZDlKbTQ3REZJRjNEOWFOZTJ4Nk4wQXdJREFRQUJBb0lDQUFybm95eHZSbEI4Z0xv
    eU00MU0wbDNxCkUxeDFLRVh2UVZrclpxdFRSTUZTZ1ZrSVlUNXJYK01HYklMM2lBWERLMFJ5cjVZ
    bmRQTjBURGNkOSt0ajlBanoKQkM0UVFuOXU2S0NId2RzUUFvWkMyYkEwZndwc3ptZUowV2V6dldj
    TkZYcVg1aE12ZjYwc1FxS0plM0xqZG12UwowM25aNVliaWdPTmx4bEU3RDMwcE1pZ2I3TDdOQXlQ
    TWlJZ3p3TVNCWE5kN0NiSFZRN0kwZEUxaDBjWmMwb21NCldVUlB5TFYzUnNJYUNXRFFzS3lzSXJP
    Um5uZDRyQk0wVkNMR0N5YTQ0OWRqMDdON20ySk1xblZRQmhtc2NEd2oKcEF2VXB4ekduOWVCQmx0
    ZFRydW5BLzB2UlN4NWlvSjdTdFpMYTRoQithVTEwS2hUMjBHWEJvZHBKUHRrMitvaQpuZFJCTmZX
    aWpLb2dzbVJnM0VUYmNuKzQ0VFV0cXdOY1hwUUloSDRxQUd1OGFmWGhJa0oveVQxYUFqN0xGRSt4
    CmV4aTAvRC9yQkEwRGd5bUVPdllEZUJud3JYYU0zeWliMHo1ZmowNkRPTDlxM0tabWUxejRiVmZG
    SDBycDdVVGkKTkQ5VHpicSt1VlFCS0NKQ1M2cUU3MFJpRloyTTEzbTdna1N4UW16L0hoeEVXWHhn
    WS9INXI1RVJSMDNjRmRNMQpLaDRNV3lQVFNzVGFvVGIzRjF4WVVTU2F5Q3RENEJVb1RRby9CbDM3
    ZVZBblQ1L3ZwWDlObWM0aUJrNXJTRWEzCm9Lc08rMXdxc29NRjB0QnZFQ2dnVXdQeTNESFZZMm9E
    Z1djaDVaby8yZmhkNWU0ZHZ4dzhvY01lQ1VUMXlQck0KekRJcHBNNHVTU1pqQ2MyekFvWWRBb0lC
    QVFEekx0ZHlJRzc4TXhtWHQ3SXhaZUZSOEhWN3BsZWNiR1l5NHR6SwpVNmIraWpEdzZKeXV0aGpN
    Q0ZTQUg3cXlRN0p5OVJ3RVp0ZG9jN0krRHRkSVBVVEkySWhKcDNIZFZhTWlacDE1CkV0VzYwRU0y
    cHUwRURKblBDalR0YmxHOUQ0Rml4ZWlpT1ZsV3RvZjdOSzBZMktpcFdmVzlodll3VllKYWFHWGIK
    QmdvdGVHNG9RN1RWSVhhMFJFSFNaLzkrQVFJejRBdFlDanBZQ2tXaVdSQ3dPcjdQa2JmVG0wZUZx
    NTFVZ2c3UgovR2ltV0FKSVdObkhZS3hjaG9jZDIxL3greURHTy9DTGdOOHNqZzY0c3JvR2U4YW5N
    aCtIQjhKTGd3S0xOVzlBCmwzTmNNR1pQb1ZrYmgvWkwxSXhtQzdmQVpjTVBTQ2V6eEVodVd2T3lP
    Ukk5cHlRRkFvSUJBUUM3WjZkWVBiQ2YKMGJEVFRrWWxkdHNDOEwvZjZOVUd5V3hvRGN4QitDeDV1
    SFBKUTBzeFZLVHBQY1krOHZKdVlLQUZ5c05rRG1pYQpIVmxEUUprSEN5MGRqaW51T25La1g4dzZR
    SkFPdkxNVnh3MkFBcWlYNXpYU3ZqTjVlT2VLTStNTVpsc3MvWDY5CjNwRnl1MG5WOHhKc2RNRnJa
    dzFDVDMyLzZoQ1R6Z2Y4TDVKVXRTWmwyVUlORXJrZ3YwajU4Y0ZaRVFDb0s5ekQKcWZLeERXMzFn
    b09RaU1uVlV5SFJVamZER0JIckU2T2x4VkxuRHE1OXFGOWMwajRERW05QVRWQ2tkZFNKd01DaAp5
    MHpQaEl1N2NKU05tRjFrTmxaeEJKUzNpWjV2Q2Q3L3hlYXYxLzlRYU5ObnNqYSt4ai9mZ2FpU2pB
    T1JjdmpsCktzaWdFTFhFdS81bkFvSUJBUUNpMVV1bi9MVzBJOWRRTXMyYnJCZHEwWE1wUDZITWVQ
    MFp0N1NWdWR2STl1bDgKZHBWcm16MFJhY2FESUR2WDMrS2VmU2VzZnR4ZjhaQjVZMkNkMjRDeVor
    TWlSbi9FNy9IVE9CamJtRlFLeWljbgpjakNrbEhkdEhlMkF5bXpyQm5YaG1KbUQvcGltcW9SMUhi
    bUdPSlQvQ09DMmJxZHNoK1ZIK2oyeG9lS3d2Y0l0CkxlRHBFWVkxZ0xyK1Uyck5pWWxiQ1BzdmtY
    R3R2L3NPa1VyT1poZWNUM3Rpc3NmNlpvWnJyc2FUcnNxNEQ1Zy8KcjFicjNQeXMyOXVmajJRNFdL
    cUNjbUpJVnh1WTd1cEduRTVaeHdtbXJMWlZxVWxkWExVWVY4aE4zTnQrOEYyaApsbTFmTlBRanBJ
    ZjZVSUJTMFJFQ3E1TUNHVDFTdjQ0TVdaQ3dQYm10QW9JQkFRQ0NlTURHSzNUYlg4Ym01ampwCi9s
    eXVLR1M5ZzhGRUQxbTgrOVk0RzRzRFYwcXRWWDkxSWNRS2FxcXB5c1REMmR1dkRLS0o5NG9WdWRj
    YWZrL0wKMnBrWFdaR1J2UGx4dlF4WGhmbUZlUlNKVmVMdE8yeWJEU3FveFNqYktqU3hRRHlUdG5O
    RjJGcXozOCtOZkIwRQpxazBxV3dNS1BsMjV5OVAxbUFUZ2tuRjJ2cnYyNDRPUEp2bllWaSt6UDlt
    VHdoOWxYZlFDSVQ5NnJjZzhRZWhMCkpBbHF5QUVVMXVMVmM1TkU3VzRVSnNFcE9UN2xoSkF4QmRj
    V3JYems4S0dwdCtvc0JhanFHdHRDQ1dNNW1zTVoKeFdCM1VCdTlHQ09JWGJNWU1PU3YwOFNBZUF5
    S1lpdnJsSCtTVXozUUJnQVVJSlgzS1NtV3l0L0QxTXlHdS91QQpzNDJEQW9JQkFRQ1YvcWRTeVhh
    cmZGajFHelJYOWhxazE5SDk2R1Q5R1NuUXJveDM0STlpcHdTb2VhdGFxT0htCmRRSWtObWY1emZF
    TitYNGNDWE5LSExzVzNueHB1NnpqaVpoaHFMYnpZODRMZHc0aDJPRThwcUptLzVzeDNza3oKb2tW
    dlZLMitjTS9DcUFiU2tWTlBxWmlnNUpxRVU2SzV4RWJWYnJacU9SYkg0dm5FaTNOY004bjNDM0Fl
    US83Ywo0OUtQMG5VczU0VWlidXorTmtLbjQwbG5Md2QvdkFVNGhtVk03QjBXOXJ6b25oRTZYWFk5
    S2E4ZDJNYUp0ejlWCnFWdDU0NjBMSnJadGFTSGdjZFVwRDlyNW1jNGhUWmltUERLcE9rd2lCVVZC
    dEZZNWN4Ry9xVjFscktmRExjS2QKV251TmhDUUs2Ym9abjlFYS9TUE95cDZlRXdFcFdEV2gKLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=