app:
  desc: k8s_demo
  version: v1.0.0
  addr: 0.0.0.0:40814
  env: dev
  TimeFormat: "2006-01-02 15:04:05"
mysql:
  enable: true
  masterHost: 127.0.0.1
  slaverHost:
  port: 3306
  user: root
  password: root
  database: k8s_demo
  charset: utf8mb4 # 要支持完整的UTF-8编码,需设置成: utf8mb4
  parseTime: true # 解析time.Time类型
  timeZone: Asia%2fShanghai # 时区,若设置 Asia/Shanghai,需写成: Asia%2fShanghai
  slowSql: 500ms # 慢sql时间。单位毫秒
  logLevel: info # error、info、warn
  ignoreRecordNotFoundError: true # 是否忽略ErrRecordNotFound(未查到记录错误)
  gorm: # gorm配置项disableForeignKeyConstraintWhenMigrating
    skipDefaultTx: false # 是否跳过默认事务
    singularTable: true # 是否使用单数表名(默认复数)，启用后，User结构体表将是user
    prepareStmt: false # 执行任何SQL时都会创建一个prepared statement并将其缓存，以提高后续的效率
    disableForeignKeyConstraintWhenMigrating: true #在AutoMigrate 或 CreateTable 时，GORM 会自动创建外键约束，若要禁用该特性，可将其设置为 true
redis:
  enable: true
  addrs: 
    - 127.0.0.1:6379
  password: "MucpNx6VQYdwLHmn" # 密码(可为空)
  defaultDB: 0 # 默认DB
  dialTimeout: 1s
  
