apiVersion: v1
kind: Service
metadata:
  name: dashoard-web
  namespace: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kong
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8443
