apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-client
  labels:
    app: https-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: https-client
  template:
    metadata:
      labels:
        app: https-client
    spec:
      containers:
      - name: https-client
        image: https-client:v1.0
        imagePullPolicy: IfNotPresent
        args: 
          - - URL
          - https://https-server:8080
        command: 
          - /app/https-client
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        env: 
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: https-client-config
                key: APP_ENV
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: https-client-config