apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-back-front-service
  namespace: prod
  labels:
    name: k8s-demo-back-front-service
spec:
  selector:
    app: k8s-demo-back-front
  ports:
    - protocol: TCP
      name: web
      port: 80     
      targetPort: 80  
  clusterIP: None
