apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: prod
data:
  master.cnf: |
    # 主节点MySQL的配置文件
    [mysqld]
    log-bin
  slave.cnf: |
    # 从节点MySQL的配置文件
    [mysqld]
    log-bin
    read_only=1
    replicate_ignore_db=information_schema
    replicate_ignore_db=performance_schema
    replicate_ignore_db=mysql
    replicate_ignore_db=sys
  init.sh: |
    #!/bin/bash
    REPLIC_USER=$(echo "$REPLIC_USER" | tr -d '\r\n')
    REPLIC_PASSWORD=$(echo "$REPLIC_PASSWORD" | tr -d '\r\n') 
    until mysql  -p"$MYSQL_ROOT_PASSWORD" -e "select 1;"; do sleep 1; done
    [[ $HOSTNAME =~ -([0-9]+) ]] || exit 1
    ordinal=${BASH_REMATCH[1]}
    if [[ $ordinal -eq 0 ]]; then
      mysql -p"$MYSQL_ROOT_PASSWORD" -e "grant replication slave on *.* to '$REPLIC_USER'@'%' identified by '$REPLIC_PASSWORD'"
      mysql -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES"
    else
      mysql -p"$MYSQL_ROOT_PASSWORD" -e "change master to master_host='mysql-0.mysql-svc',master_user='$REPLIC_USER',master_password='$REPLIC_PASSWORD';"
      mysql -p"$MYSQL_ROOT_PASSWORD" -e "start slave"
    fi