apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: prod
type: Opaque
data:
  pass: NlFBMFpGSTRUYzZ6UmU5VWc4amI= #6QA0ZFI4Tc6zRe9Ug8jb
  rep_pass: bWtzdFE2M3ZuYmFQeUJ5eGR6Z3Y= #mkstQ63vnbaPyByxdzgv
  rep_user: cmVw #rep
