apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: http-client-config
    literals:
      - APP_ENV=uat

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: http-client
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - URL
          - "https://ssl.test.com"



