apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-create
  namespace: prod
spec:
  template:
    spec:
      containers:
      - name: redis-cli
        image: redis:7.4
        env:
        - name: REDISCLI_AUTH
          valueFrom:
            secretKeyRef:
              name: redis
              key: pass
        command: ["/bin/sh", "-c"]
        args:
          - |
            redis-cli --cluster create \
              redis-0.redis-svc:6379 \
              redis-1.redis-svc:6379 \
              redis-2.redis-svc:6379 \
              redis-3.redis-svc:6379 \
              redis-4.redis-svc:6379 \
              redis-5.redis-svc:6379 \
              --cluster-replicas 1 -a $REDISCLI_AUTH --cluster-yes
      restartPolicy: Never
  backoffLimit: 1
